title: "Quit Social Media"
email: tommiboom@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Enjoying the internet and social life independently from big intrusive and addictive platforms
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quitsocialmedia.club" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xplosionmind
github_username: xplosionmind
git_repository: "quit-social-media"
future: true
profile: true
livereload: true
strict_front_matter: true

collections:
  posts:
    excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

sass:
    style: compressed

permalink: "/:title"
ref: ":title"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      ref: ":title"
      lang: "en"
      img: "/images/preview.gif"
      primary: "#FCC920"

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "it"
      permalink: "/:title"
      excerpt_separator: "<!--more-->"
